/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package airline.project;

import static airline.project.GlobalVariables.password;
import static airline.project.GlobalVariables.url;
import static airline.project.GlobalVariables.username;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author bhasin
 */
public class CostumerDetails extends javax.swing.JFrame {
    
    File myfile;
    public int id;
    String email;
    String imagename;
    
    public CostumerDetails() {
        initComponents();
        
        
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Costumer Details");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Email*");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 320, 60, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name*");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 180, 90, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Last Name*");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 220, 82, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Passport Number*");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 270, 130, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("DOB*");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 360, 40, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address Line *");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 430, 101, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("City*");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 320, 36, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("State*");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 220, 46, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Pin Code*");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 260, 70, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Please provide the following details.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 140, 260, 22);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 180, 160, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 220, 160, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(130, 310, 160, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(410, 210, 160, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(410, 310, 160, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(130, 350, 160, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 390, 170, 120);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(410, 260, 160, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Here", "India", "Canada", "United States Of America", "Sri Lanka", "United Kingdom", "Spain", "France", "Brazil", "Pakistan", "Bangladesh", "Australia", "South Africa", "Afghanistan", "New Zealand", "West Indies", "South Africa" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(410, 170, 170, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("ADD");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(360, 20, 80, 50);

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 130, 830, 10);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Phone*");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(340, 360, 60, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Gender*");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(340, 410, 60, 17);

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(410, 360, 160, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("Female");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(500, 410, 93, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("Male");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(410, 410, 80, 25);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Country*");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(330, 180, 66, 17);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 255, 0));
        jButton3.setText("ADD CUSTOMER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(600, 470, 190, 30);

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField3);
        jFormattedTextField3.setBounds(150, 260, 150, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("Fields marked * are complusory to fill");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(570, 450, 240, 15);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("COSTUMER DETAILS");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(250, 30, 420, 100);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(740, 20, 60, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 820, 550);

        setSize(new java.awt.Dimension(814, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                Connection myconnection;
                
                int a=4;
                
                
                
                email=jTextField4.getText().toString();
                
                if(jTextField1.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jTextField2.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jTextField4.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jTextField5.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jTextField6.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jTextArea1.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jFormattedTextField1.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jFormattedTextField2.equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jFormattedTextField3.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jComboBox1.getSelectedItem().toString().equals("Choose Here"))
                        
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jDateChooser1.getDate().toString().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(!(jRadioButton1.isSelected() || jRadioButton2.isSelected()))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
              
                else
                {
                
                
                
                if(email.contains("@") && email.contains(".") && (email.indexOf(".")-email.indexOf("@"))>Math.abs(a))
                     {
             
           boolean flag=false;
 
                if(myfile!=null)
                {
                if(myfile.length()<300000)
                {
                imagename=new java.util.Date().getTime() + myfile.getName();
                int i;

                FileInputStream rd = null;
                FileOutputStream outs = null;

                try {

                rd = new FileInputStream(myfile);
                outs = new FileOutputStream("C:\\Users\\bhasin\\Desktop\\Images\\"+imagename);//writing the new file in 'Images' folder, in the project
                byte[] b = new byte[2048]; //cache of 2kb
                while ((i = rd.read(b)) !=-1) {
                outs.write(b, 0, i); //copying from pictures to empimages byte by byte
                }
                }
                catch (Exception e) 
                {
                JOptionPane.showMessageDialog(rootPane, "error" + e.getMessage());
                e.printStackTrace();
                } 
                flag=true;
                }
                else
                {
                flag=false;
                }
                }
                else
                {
                imagename="defalutprofilepic.jpg";
                flag=true;
                } 



                if(flag)
                {

        
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="insert into customertable(Firstname,Lastname,Passport,DOB,Address,Country,State,Pincode,City,Phone,Gender,Email,DateTime) values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
             java.util.Date date=new java.util.Date();
             SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
             SimpleDateFormat format2=new SimpleDateFormat("yyyy-MM-dd");
             
             statement.setString(1,jTextField1.getText());
             statement.setString(2,jTextField2.getText());
             statement.setString(3,jFormattedTextField3.getText());
             statement.setString(4,format2.format(jDateChooser1.getDate()));
             statement.setString(5,jTextArea1.getText());
             statement.setString(6,jComboBox1.getSelectedItem().toString());
             statement.setString(7,jTextField5.getText());
             statement.setString(8,jFormattedTextField1.getText());
             statement.setString(9,jTextField6.getText());
             statement.setString(10,jFormattedTextField2.getText());
             statement.setString(11,(jRadioButton2.isSelected()?"Male":"Female"));
             statement.setString(12,jTextField4.getText());
             statement.setString(13,format.format(date));
           
             if(statement.executeUpdate()>0)
             {
                  
                 JOptionPane.showMessageDialog(rootPane,"Saved Successfully");
                 this.dispose();
                     
             }
             
             statement.close();
             jTextField1.setText("");
             jTextField2.setText("");
             
             buttonGroup1.clearSelection();
             jTextArea1.setText("");
             jComboBox1.setSelectedIndex(0);
             
         
        
       
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 }
                     }
                     }
        else
                 JOptionPane.showMessageDialog(rootPane,"Invalid Email-ID");
                
                }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CostumerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CostumerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CostumerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CostumerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CostumerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
