/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package airline.project;

import static airline.project.GlobalVariables.password;
import static airline.project.GlobalVariables.url;
import static airline.project.GlobalVariables.username;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author bhasin
 */
public class FlightDetails extends javax.swing.JFrame {

    
    public FlightDetails() {
        initComponents();
        
        Connection myconnection;
      
        
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="select City from city";
             
             com.mysql.jdbc.PreparedStatement statement=(com.mysql.jdbc.PreparedStatement) myconnection.prepareStatement(query);
             ResultSet set=statement.executeQuery();
             
             if(set.next())
             {
                 jComboBox1.removeAllItems();
                 jComboBox2.removeAllItems();
                 jComboBox1.addItem("Choose Now");
                 jComboBox2.addItem("Choose Now");
                 do
                 {
                     jComboBox2.addItem(set.getString("City"));
                     jComboBox1.addItem(set.getString("City"));
                     
                 }while(set.next());
                 
             }
             statement.close();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 }
        
        
        }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flight Details");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("(Hours:Minutes)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 350, 130, 11);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Flight ID*");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 180, 90, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("Flight Name*");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 220, 100, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setText("Source*");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 270, 70, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 255));
        jLabel5.setText("Flight Class*");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 370, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jLabel6.setText("Flight Charges (in Rs.)*");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 190, 150, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 255));
        jLabel9.setText("Arrival Time*");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 330, 90, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 255));
        jLabel10.setText("Flight Date*");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(292, 240, 80, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Please provide the following details.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 140, 260, 22);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 180, 160, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(120, 220, 160, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(120, 310, 160, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(380, 320, 160, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("FLIGHT DETAILS");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(400, 10, 400, 110);

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 120, 1270, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 255));
        jLabel16.setText("Business Seats*");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(310, 420, 98, 15);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 255, 0));
        jButton3.setText("UPDATE FLIGHT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1080, 480, 147, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("Fields marked * are complusory to fill while adding flight.");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(370, 490, 350, 15);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 255, 0));
        jButton4.setText("DELETE FLIGHT");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(740, 480, 170, 30);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 255, 0));
        jButton5.setText("Search");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(550, 280, 100, 30);

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 255, 0));
        jButton18.setText("ADD FLIGHT");
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(920, 480, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 255));
        jLabel8.setText("Departure Time*");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 320, 110, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 255));
        jLabel13.setText("(Hours:Minutes)");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 340, 90, 11);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(460, 180, 140, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Flight Name", "Departure Time", "Arrival Time", "E Seats Left", "B Seats Left"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(657, 151, 600, 300);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 255));
        jLabel15.setText("Flight Type*");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(310, 160, 75, 15);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(380, 230, 160, 30);

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(420, 410, 160, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 255));
        jLabel17.setText("Economy Seats*");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(290, 380, 101, 15);

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField3);
        jFormattedTextField3.setBounds(400, 370, 160, 30);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBox1.setText("Business");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(190, 360, 90, 25);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBox2.setText("Economy");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(91, 360, 90, 25);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 255));
        jLabel18.setText("(Business)");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(340, 210, 70, 15);

        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(jFormattedTextField4);
        jFormattedTextField4.setBounds(160, 410, 140, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 255));
        jLabel19.setText("Flight Charges (in Rs.)*");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 420, 150, 15);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 255));
        jLabel21.setText("(Economy)");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 440, 70, 15);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 255));
        jLabel22.setText("Destination*");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(290, 280, 79, 15);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton1.setText("Domestic");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(510, 150, 90, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton2.setText("International");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(390, 150, 110, 25);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1180, 20, 60, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(380, 270, 160, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(120, 270, 160, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1270, 560);

        setSize(new java.awt.Dimension(1261, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int col=0;
        int row=jTable2.getSelectedRow();
        String id=(String) jTable2.getValueAt(row, col);
        
        Connection myconnection;
        
         if(jTextField1.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jTextField2.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jTextField4.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jTextField5.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jComboBox1.getSelectedItem().toString().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                 else if(jComboBox2.getSelectedItem().toString().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                  else if(jFormattedTextField1.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                
                else if(jFormattedTextField2.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
               
                else if(!(jCheckBox1.isSelected() || jCheckBox2.isSelected()))
                        
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
         else
                {
        
       
        
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="update flighttable set Flightname=?,Source=?,Destination=?,Arrivaltime=?,Departuretime=?,Flightclass=?,Flighttype=?,FlightchargesE=?,FlightchargesB=?,Flightdate=?,Bseats=?,Eseats=?,DateTime=? where Flight_ID=?";
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
             java.util.Date date=new java.util.Date();
             SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
             SimpleDateFormat format2=new SimpleDateFormat("yyyy-MM-dd");
             
             
             statement.setString(14,id);
             statement.setString(1,jTextField2.getText());
             statement.setString(2,jComboBox2.getSelectedItem().toString());
             statement.setString(3,jComboBox1.getSelectedItem().toString());
             statement.setString(4,(jTextField5.getText()));
             statement.setString(5,(jTextField4.getText()));
             statement.setString(6,jCheckBox1.isSelected()?(jCheckBox2.isSelected()?"Business,Economy":"Business"):"Economy");
             statement.setString(7,jRadioButton1.isSelected()?"Domestic":"International");
             statement.setString(8,jFormattedTextField4.getText());
             statement.setString(9,jFormattedTextField1.getText());
             statement.setString(10,format2.format(jDateChooser1.getDate()));
             statement.setInt(11,Integer.parseInt(jFormattedTextField2.getText()));
             statement.setInt(12,Integer.parseInt(jFormattedTextField3.getText()));
             statement.setString(13,format.format(date));
            
             if(statement.executeUpdate()>0)
             {
                  
                 JOptionPane.showMessageDialog(rootPane,"Flight Updated Successfully");
                 
             jTextField2.setText("");
             jComboBox2.setSelectedIndex(0);
             jComboBox2.setSelectedIndex(0);
             jCheckBox1.setSelected(false);
             jCheckBox2.setSelected(false);
             buttonGroup1.clearSelection();
             jFormattedTextField1.setText("");
             jFormattedTextField4.setText("");
             jFormattedTextField2.setText("");
             jTextField1.setText("");
             jTextField4.setText("");
             jTextField5.setText("");
             jDateChooser1.setDate(null);
             jTextField1.requestFocus();
             jFormattedTextField3.setText("");
             
                     
             }
             
             statement.close();
             
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             e.printStackTrace();
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                     e.printStackTrace();
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 }
                }
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        DefaultTableModel m1=(DefaultTableModel) jTable2.getModel();
        
        int ans=JOptionPane.showConfirmDialog(rootPane,"Do you want to delete record ?", "Confirm Deletion",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
        
        Connection myconnection;
        
         try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
            
        try
        {
             String query="insert into deletedflights values(?,?,?,?,?,?)";
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
             java.util.Date date=new java.util.Date();
             SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
             SimpleDateFormat format2=new SimpleDateFormat("yyyy-MM-dd");
             
             
             statement.setString(1,jTextField1.getText());
             statement.setString(2,jTextField2.getText());
             statement.setString(3,jComboBox2.getSelectedItem().toString());
             
             statement.setString(4,jComboBox1.getSelectedItem().toString());
             statement.setString(5,format2.format(jDateChooser1.getDate()));
             
             statement.setString(6,format.format(date));
             statement.executeUpdate();
             
             
                     
             
             
             statement.close();
             
        
        }   
         
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             e.printStackTrace();
         }
         

        
       
         try
         {
             String query="delete from flighttable where Flight_ID = ?";
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
             
             
             statement.setString(1,jTextField1.getText());
             
             
             if(statement.executeUpdate()>0)
             {
                 JOptionPane.showMessageDialog(rootPane,"Flight Deleted Successfully");
             }
             
             statement.close();
             
             m1.setRowCount(0);
             jTextField2.setText("");
            
             jCheckBox1.setSelected(false);
             jCheckBox2.setSelected(false);
             buttonGroup1.clearSelection();
             jFormattedTextField1.setText("");
             jFormattedTextField4.setText("");
             jFormattedTextField2.setText("");
             jTextField1.setText("");
             jTextField4.setText("");
             jTextField5.setText("");
             jDateChooser1.setDate(null);
             jTextField1.requestFocus();
             jFormattedTextField3.setText("");
             
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 }
        }
   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Connection myconnection;
        
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="select Flight_ID,Flightname,Arrivaltime,Departuretime,Bseats,Eseats from flighttable where Source=? and Destination=? ";
             
             
             com.mysql.jdbc.PreparedStatement statement=(com.mysql.jdbc.PreparedStatement) myconnection.prepareStatement(query);
             statement.setString(1,jComboBox2.getSelectedItem().toString());
             statement.setString(2,jComboBox1.getSelectedItem().toString());
             
             ResultSet set=statement.executeQuery();
             
             DefaultTableModel m1=(DefaultTableModel) jTable2.getModel();
             TableColumnModel m2=jTable2.getColumnModel();
             m2.getColumn(2).setPreferredWidth(100);
             m2.getColumn(3).setPreferredWidth(100);
             m2.getColumn(1).setPreferredWidth(100);
             m2.getColumn(5).setPreferredWidth(130);
             m2.getColumn(4).setPreferredWidth(130);
 
             jTable2.setRowHeight(40);
             
             
             if(set.next())
             {
                 m1.setRowCount(0);
                 do
                 {
                     String name,phone,address,gender,course,sbcourse;
                     name=set.getString("Flight_ID");
                     phone=set.getString("Flightname");
                     course=set.getString("Arrivaltime");
                     sbcourse=set.getString("Departuretime");
                     int dob=set.getInt("Bseats");
                     int dob2=set.getInt("Eseats");
                     
                     m1.addRow(new Object[]{name,phone,sbcourse,course,dob2,dob});
                 }while(set.next());
                 
                 
             }
             else{
                 m1.setRowCount(0);
                 JOptionPane.showMessageDialog(rootPane,"No Flights Avaliable");
             
                 
             }
           
            statement.close();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        
         Connection myconnection;
                
                
                
                if(jTextField1.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jTextField2.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jTextField4.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jTextField5.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                else if(jComboBox1.getSelectedItem().toString().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                 else if(jComboBox2.getSelectedItem().toString().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                  else if(jFormattedTextField1.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                
                else if(jFormattedTextField2.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
               
                else if(!(jCheckBox1.isSelected() || jCheckBox2.isSelected()))
                        
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
                
                else
                {
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="insert into flighttable values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
             java.util.Date date=new java.util.Date();
             SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
             SimpleDateFormat format2=new SimpleDateFormat("yyyy-MM-dd");
             
             
             statement.setString(1,jTextField1.getText());
             statement.setString(2,jTextField2.getText());
             statement.setString(3,jComboBox2.getSelectedItem().toString());
             statement.setString(9,jFormattedTextField4.getText());
             statement.setString(4,(jTextField5.getText()));
             statement.setString(5,(jTextField4.getText()));
             statement.setString(6,jCheckBox1.isSelected()?(jCheckBox2.isSelected()?"Business,Economy":"Business"):"Economy");
             statement.setString(7,jRadioButton1.isSelected()?"Domestic":"International");
             statement.setString(8,jFormattedTextField1.getText());
             statement.setString(10,jComboBox1.getSelectedItem().toString());
             statement.setString(11,format2.format(jDateChooser1.getDate()));
             statement.setInt(12,Integer.parseInt(jFormattedTextField2.getText()));
             statement.setInt(13,Integer.parseInt(jFormattedTextField3.getText()));
             statement.setString(14,format.format(date));
            
             if(statement.executeUpdate()>0)
             {
                  
                 JOptionPane.showMessageDialog(rootPane,"Flight Saved Successfully");
                 
             jTextField2.setText("");
             jComboBox2.setSelectedItem("");
             jComboBox1.setSelectedItem("");
             jCheckBox1.setSelected(false);
             jCheckBox2.setSelected(false);
             buttonGroup1.clearSelection();
             jFormattedTextField1.setText("");
             jFormattedTextField4.setText("");
             jFormattedTextField2.setText("");
             jTextField1.setText("");
             jTextField4.setText("");
             jTextField5.setText("");
             jDateChooser1.setDate(null);
             jTextField1.requestFocus();
             jFormattedTextField3.setText("");
                     
             }
                     
             
             
             statement.close();
             
        
             
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             e.printStackTrace();
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                     e.printStackTrace();
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 }
                }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        
        int col=0;
        int row=jTable2.getSelectedRow();
        String id=(String) jTable2.getValueAt(row, col);
        
        Connection myconnection;
      
               
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="select * from flighttable where Flight_ID = ?";
             com.mysql.jdbc.PreparedStatement statement=(com.mysql.jdbc.PreparedStatement) myconnection.prepareStatement(query);
             statement.setString(1,id);
             ResultSet set=statement.executeQuery();
             
             if(set.next())
             {
                 jTextField1.setText(set.getString("Flight_ID"));
                 jTextField2.setText(set.getString("Flightname"));
                 jTextField5.setText(set.getString("Arrivaltime"));
                 jFormattedTextField1.setText(set.getString("FlightchargesB"));
                 jFormattedTextField4.setText(set.getString("FlightchargesE"));
                 jComboBox2.setSelectedItem(set.getString("Source"));
                 jComboBox1.setSelectedItem(set.getString("Destination"));
                 jFormattedTextField2.setText(set.getString("Bseats"));
                 jFormattedTextField3.setText(set.getString("Eseats"));
                 if(set.getString("Flightclass").equalsIgnoreCase("Business"))
                 {
                  jCheckBox1.setSelected(true);
                 }
                 else if(set.getString("Flightclass").equalsIgnoreCase("Economy"))
                 {
                   jCheckBox2.setSelected(true);
                 }
                 else
                 {
                     jCheckBox1.setSelected(true);
                     jCheckBox2.setSelected(true);
                 }
                 
                 if(set.getString("Flighttype").equalsIgnoreCase("Domestic"))
                 {
                  jRadioButton1.setSelected(true);
                 }
                 else if(set.getString("Flighttype").equalsIgnoreCase("International"))
                 {
                   jRadioButton2.setSelected(true);
                 }
                     
                 jTextField4.setText(set.getString("Departuretime"));
                 jDateChooser1.setDate(set.getDate("Flightdate"));
                 
                 
             }
             statement.close();
             
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 }

    }//GEN-LAST:event_jTable2MousePressed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
