/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.project;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author bhasin
 */
public class List extends javax.swing.JFrame implements GlobalVariables{

    /**
     * Creates new form List
     */
    public List() {
        initComponents();
        
        
        Connection myconnection;
      
        
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="select city from city";
             
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
             ResultSet set=statement.executeQuery();
             
             if(set.next())
             {
                 jComboBox1.removeAllItems();
                 jComboBox2.removeAllItems();
                 jComboBox1.addItem("Choose Now");
                 jComboBox2.addItem("Choose Now");
                 do
                 {
                     jComboBox2.addItem(set.getString("City"));
                     jComboBox1.addItem(set.getString("City"));
                     
                 }while(set.next());
                 
             }
             statement.close();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("LIST OF FLIGHTS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 20, 410, 44);

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 110, 1000, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Flight Name", "Departure Time", "Arrival Time", "Source", "Destination", "Flight Type", "Economy Seats Left", "Business Seats Left"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 210, 970, 280);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Source");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 140, 42, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Destination");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 140, 71, 15);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Here" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(290, 130, 132, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Here" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(60, 130, 131, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 255, 0));
        jButton1.setText("Get Flights");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(680, 130, 120, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 255));
        jLabel12.setText("Flight Type");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(202, 180, 90, 17);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(500, 130, 160, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 255, 0));
        jButton3.setText("Get All Flights Of This Type On This Date");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 170, 290, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 255));
        jLabel13.setText("Flight Date");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(430, 140, 72, 15);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBox2.setText("Domestic");
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(300, 170, 90, 30);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 204));
        jCheckBox1.setText("International");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(400, 170, 110, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(910, 10, 60, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1010, 530);

        setSize(new java.awt.Dimension(995, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection myconnection;
        
            
        
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="select Flight_ID,Flighttype,Flightname,Flightdate,Source,Destination,Arrivaltime,Departuretime,Bseats,Eseats from flighttable where Source=? and Destination=? and Flightdate=?";
             
             SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
             
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
             statement.setString(1, jComboBox2.getSelectedItem().toString());
             statement.setString(2, jComboBox1.getSelectedItem().toString());
             statement.setString(3, format.format(jDateChooser1.getDate()));
             
             ResultSet set=statement.executeQuery();
             
             DefaultTableModel m1=(DefaultTableModel) jTable2.getModel();
             TableColumnModel m2=jTable2.getColumnModel();
             m2.getColumn(2).setPreferredWidth(100);
             m2.getColumn(3).setPreferredWidth(80);
             m2.getColumn(0).setPreferredWidth(60);
             m2.getColumn(5).setPreferredWidth(120);
             m2.getColumn(6).setPreferredWidth(100);
             m2.getColumn(7).setPreferredWidth(120);
             m2.getColumn(8).setPreferredWidth(120);
             m2.getColumn(1).setPreferredWidth(80);

             
             jTable2.setRowHeight(40);
             
             
             if(set.next())
             {
                 m1.setRowCount(0);
                 do
                 {
                     String name,phone,course,sbcourse,dob,dob2;
                     name=set.getString("Flight_ID");
                     phone=set.getString("Flightname");
                     course=set.getString("Arrivaltime");
                     sbcourse=set.getString("Departuretime");
                     dob=set.getString("Eseats");
                     String hi=set.getString("Source");
                     String bi=set.getString("Destination");
                     dob2=set.getString("Bseats");
                     String type=set.getString("Flighttype");
                     
                     m1.addRow(new Object[]{name,phone,sbcourse,course,hi,bi,type,dob,dob2});
                 }while(set.next());
                 
                 
             }
             else{
                 m1.setRowCount(0);
                 JOptionPane.showMessageDialog(rootPane,"No Flights Avaliable");
             
                 
             }
           
            statement.close();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Connection myconnection;
        
      
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="select Flight_ID,Flightname,Flightdate,Flighttype,Source,Destination,Arrivaltime,Departuretime,Bseats,Eseats from flighttable where Flightdate=?";
             
             SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
             
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
           
             statement.setString(1, format.format(jDateChooser1.getDate()));
             
             ResultSet set=statement.executeQuery();
             
             DefaultTableModel m1=(DefaultTableModel) jTable2.getModel();
             TableColumnModel m2=jTable2.getColumnModel();
             m2.getColumn(2).setPreferredWidth(100);
             m2.getColumn(3).setPreferredWidth(80);
             m2.getColumn(0).setPreferredWidth(60);
             m2.getColumn(5).setPreferredWidth(120);
             m2.getColumn(6).setPreferredWidth(100);
             m2.getColumn(7).setPreferredWidth(120);
             m2.getColumn(8).setPreferredWidth(120);
             m2.getColumn(1).setPreferredWidth(80);
             
             jTable2.setRowHeight(40);
             
             
             if(set.next())
             {
                 m1.setRowCount(0);
                 
                 jComboBox1.setSelectedIndex(0);
                 jComboBox2.setSelectedIndex(0);
                 do
                 {
                     String name,phone,course,sbcourse,hi,bi,type;
                     name=set.getString("Flight_ID");
                     phone=set.getString("Flightname");
                     course=set.getString("Arrivaltime");
                     sbcourse=set.getString("Departuretime");
                     int dob=set.getInt("Eseats");
                     hi=set.getString("Source");
                     bi=set.getString("Destination");
                     int dob2=set.getInt("Bseats");
                     type=set.getString("Flighttype");
                     
                     if(jCheckBox1.isSelected() && jCheckBox2.isSelected())
                     {
                     m1.addRow(new Object[]{name,phone,sbcourse,course,hi,bi,type,dob,dob2});
                     }
                     
                     else if(jCheckBox1.isSelected() && !(jCheckBox2.isSelected()))
                     {
                         if(set.getString("Flighttype").equalsIgnoreCase("International"))
                     m1.addRow(new Object[]{name,phone,sbcourse,course,hi,bi,type,dob,dob2});
                         else
                             JOptionPane.showMessageDialog(rootPane,"No International Flights On This Date");
                     }
                     
                     else if(!(jCheckBox1.isSelected()) && jCheckBox2.isSelected())
                     {
                         if(set.getString("Flighttype").equalsIgnoreCase("Domestic"))
                            m1.addRow(new Object[]{name,phone,sbcourse,course,hi,bi,type,dob,dob2});
                         
                         else
                             JOptionPane.showMessageDialog(rootPane,"No Domestic Flights On This Date");
                     }
                     
                     jCheckBox1.setSelected(false);
                     jCheckBox2.setSelected(false);
                     
                 }while(set.next());
                 
                 
             }
             else{
                 m1.setRowCount(0);
                 JOptionPane.showMessageDialog(rootPane,"No Flights Avaliable");
             
                 
             }
           
            statement.close();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 }
         
         
         

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
