/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author bhasin
 */
public class RegistrationForm3 extends javax.swing.JFrame implements GlobalVariables{

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm3() {
        initComponents();
        jTextField1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Account");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 130, 60, 20);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 180, 90, 20);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Usertype");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 230, 90, 20);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Security Question");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 320, 150, 20);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 400, 70, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 140, 260, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 180, 260, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(190, 360, 270, 30);

        jPasswordField1.setEchoChar('*');
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(190, 270, 260, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose From Here", "What was the house number you lived in as a child?", "What is your best friend's name?", "What were the last four digits of your telephone number?", "What primary school did you attend?", "In what town or city was your first full time job?" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(190, 320, 270, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 255, 0));
        jButton2.setText("REGISTER");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 440, 170, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(500, 20, 60, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("USER/ADMIN ACCOUNT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 70, 380, 40);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Answer");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 360, 80, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 51, 204));
        jRadioButton1.setText("Male");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(190, 400, 80, 20);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 51, 204));
        jRadioButton2.setText("Female");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(280, 400, 90, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Show Password");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 280, 110, 20);

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 120, 580, 10);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 270, 90, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Here", "Admin", "User" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(190, 230, 260, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 580, 520);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("UPDATE");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(240, 30, 140, 40);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 255, 0));
        jButton6.setText("DELETE FLIGHT");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(740, 480, 170, 30);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 255, 0));
        jButton8.setText("DELETE RECORD");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(320, 440, 170, 40);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 0));
        jButton1.setText("Search");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 180, 100, 23);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 580, 520);

        setSize(new java.awt.Dimension(576, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Connection myconnection;
         if(jTextField1.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
          else if(jTextField2.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
          else if(jTextField3.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
          else if(jPasswordField1.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
         else if(!(jRadioButton1.isSelected() || jRadioButton2.isSelected()))
                {
                    JOptionPane.showMessageDialog(rootPane,"Fill all details");
                }
        else
         {
       
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
        
        String q2="select AdminN from adminn order by AdminN desc";
        PreparedStatement statement3=(PreparedStatement) myconnection.prepareStatement(q2);
        ResultSet Set=statement3.executeQuery();
        if(Set.next())
        {
        if((jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Admin") && (Set.getInt("AdminN")<7)) || (jComboBox1.getSelectedItem().toString().equalsIgnoreCase("User")))
        {
        
        
         try
         {
             
             
             String query="insert into login(Name,Username,Password,SecurityQ,Answer,Usertype,Gender,DateTime) values(?,?,?,?,?,?,?,?)";
             
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
             
            
             java.util.Date date=new java.util.Date();
             SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
             
             if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Admin"))
             {
                String q1="insert into adminn(datetime) values(?)"; 
                PreparedStatement statement2=(PreparedStatement) myconnection.prepareStatement(q1);
                statement2.setString(1,format.format(date));
                statement2.executeUpdate();
             }
             
            
             jTextField1.requestFocus();
             statement.setString(1,jTextField1.getText());
             statement.setString(2,jTextField2.getText());
             statement.setString(3,jPasswordField1.getText());
             statement.setString(4,jComboBox2.getSelectedItem().toString());
             statement.setString(5,jTextField3.getText());
             statement.setString(6,jComboBox1.getSelectedItem().toString());
             statement.setString(7,(jRadioButton1.isSelected()?"Male":"Female"));
             statement.setString(8,format.format(date));
             
             
             if(statement.executeUpdate()>0 )
             {
                 
                 JOptionPane.showMessageDialog(rootPane,"Saved Successfully");
             }
             statement.close();
             jTextField1.setText("");
             jTextField2.setText("");
             jTextField3.setText("");
             buttonGroup1.clearSelection();
             jPasswordField1.setText("");
             jComboBox2.setSelectedIndex(0);
             
              
        this.dispose(); 
             
         
        
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             e.printStackTrace();
         }
         finally
         {
             myconnection.close();
         }
        }
        else
            JOptionPane.showMessageDialog(rootPane,"Cannot Add More Admins");
        }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 e.printStackTrace();
                 }

        
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        jPasswordField1.setEchoChar((char)0);
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        jPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        int ans=JOptionPane.showConfirmDialog(rootPane,"Do you want to delete record ?", "Confirm Deletion",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {

            Connection myconnection;

            try
            {

                myconnection=DriverManager.getConnection(url, username,password);
                try
                {
                    String query="delete from flighttable where Flight_ID = ?";
                    PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);

                    statement.setString(1,jTextField1.getText());

                    if(statement.executeUpdate()>0)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Record Deleted Successfully");
                    }

                    statement.close();

                    jTextField2.setText("");
                    jTextField3.setText("");
                    jComboBox1.setSelectedIndex(0);
                    jComboBox2.setSelectedIndex(0);
                    buttonGroup1.clearSelection();
                    jTextField1.setText("");
                    jTextField1.requestFocus();

                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());

                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        int ans=JOptionPane.showConfirmDialog(rootPane,"Do you want to delete record ?", "Confirm Deletion",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {

            Connection myconnection;

            try
            {

                myconnection=DriverManager.getConnection(url, username,password);
                try
                {
                    String query="delete from login where Username = ?";
                    PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);

                    statement.setString(1,jTextField2.getText());

                    if(statement.executeUpdate()>0)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Record Deleted Successfully");
                    }

                    statement.close();

                    jTextField2.setText("");
                    jTextField3.setText("");
                    jComboBox1.setSelectedIndex(0);
                    jComboBox2.setSelectedIndex(0);
                    buttonGroup1.clearSelection();
                    jTextField1.setText("");
                    jTextField1.requestFocus();

                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());

                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection myconnection;

        try
        {

            myconnection=DriverManager.getConnection(url, username,password);
            try
            {
                String query="select * from login where Username = ?";
                PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
                statement.setString(1,jTextField2.getText());
                ResultSet set=statement.executeQuery();

                if(set.next())
                {
                    jTextField1.setText(set.getString("Name"));
                    jComboBox2.setSelectedItem(set.getString("SecurityQ"));
                    jComboBox1.setSelectedItem(set.getString("Usertype"));
                    if(set.getString("Gender").equalsIgnoreCase("Male"))
                    {
                        jRadioButton1.setSelected(true);
                    }
                    else
                        jRadioButton2.setSelected(true);
                    
                    jTextField3.requestFocus();

                }
                else
                JOptionPane.showMessageDialog(rootPane,"No entries avaliable");

                statement.close();

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());

            }
            finally
            {
                myconnection.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
