/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.project;

import static airline.project.GlobalVariables.password;
import static airline.project.GlobalVariables.url;
import static airline.project.GlobalVariables.username;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author bhasin
 */
public class TicketReservation extends javax.swing.JFrame {

    public static String a,b,c,d,e,f,g,h,i,j,k;
    
    
            
    public TicketReservation() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();

        jButton2.setBackground(new java.awt.Color(255, 255, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket Reservation");
        setBackground(new java.awt.Color(255, 0, 51));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("RESERVATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 80, 270, 50);

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 130, 1110, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Please provide the following details.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 150, 260, 22);

        jTabbedPane1.setBackground(new java.awt.Color(0, 51, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 102, 0));
        jTabbedPane1.setToolTipText("");

        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Date Of Journey");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 90, 120, 17);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Here" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(510, 20, 131, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("To");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(650, 30, 30, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Here" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(680, 20, 132, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("From");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(470, 27, 50, 20);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(310, 80, 170, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 255, 0));
        jButton1.setText("Proceed To Passenger Details");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(820, 380, 230, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("*B-Business  *E-Economy");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(630, 390, 180, 16);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 255, 0));
        jButton4.setText("Check Available Flights");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(520, 80, 190, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Select Class");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(830, 30, 100, 17);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Economy", "Business" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(920, 20, 110, 30);

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton2.setText("INTERNATIONAL");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(159, 20, 160, 25);

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 204));
        jRadioButton1.setText("DOMESTIC");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(330, 20, 110, 25);

        jPanel3.setBackground(new java.awt.Color(51, 255, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FLIGHT TYPE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 20, 450, 50);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Flight Name", "Departure Time", "Arrival Time", "E Class Charges", "B Class Charges", "Economy Seats Left", "Business Seats Left"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 120, 1040, 250);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-10, 0, 1090, 440);

        jTabbedPane1.addTab("Select Flight", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Email*");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(50, 190, 60, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("First Name*");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(50, 50, 90, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Last Name*");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(50, 90, 82, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("Passport Number*");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(30, 140, 130, 17);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("Address Line *");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(40, 260, 101, 17);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 204));
        jLabel21.setText("State*");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(480, 140, 46, 17);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 255, 51));
        jLabel23.setText("If Already A Member Search By Entering Passport Number!If Not Please Register First");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(10, 10, 600, 22);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Here", "India", "Canada", "United States Of America", "Sri Lanka", "United Kingdom", "Spain", "France", "Brazil", "Pakistan", "Bangladesh", "Australia", "South Africa", "Afghanistan", "New Zealand", "West Indies" }));
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(550, 90, 170, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 204));
        jLabel24.setText("Phone*");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(480, 190, 60, 17);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 204));
        jLabel25.setText("Gender*");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(460, 240, 60, 17);

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 51, 204));
        jRadioButton3.setText("Female");
        jPanel4.add(jRadioButton3);
        jRadioButton3.setBounds(620, 240, 93, 25);

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 51, 204));
        jRadioButton4.setText("Male");
        jPanel4.add(jRadioButton4);
        jRadioButton4.setBounds(530, 240, 80, 25);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 204));
        jLabel26.setText("Country*");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(470, 100, 66, 17);

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel4.add(jFormattedTextField3);
        jFormattedTextField3.setBounds(170, 130, 150, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("Fields marked * are complusory to fill");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(830, 340, 240, 15);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 255, 0));
        jButton6.setText("Proceed To Payment");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(870, 360, 180, 30);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(0, 255, 0));
        jButton7.setText("SEARCH");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);
        jButton7.setBounds(330, 130, 100, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 204));
        jLabel29.setText("CUSTOMER ID");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(440, 40, 120, 17);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 204));
        jPanel4.add(jLabel30);
        jLabel30.setBounds(560, 40, 60, 20);

        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("jLabel8");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(140, 50, 230, 16);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("jLabel16");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(140, 90, 250, 16);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("jLabel18");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(540, 140, 180, 16);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("jLabel19");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(150, 210, 260, 130);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("jLabel20");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(550, 190, 190, 16);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("jLabel22");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(110, 190, 220, 16);

        jTabbedPane1.addTab("Passenger Details", jPanel4);

        jPanel5.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 204));
        jPanel5.add(jLabel32);
        jLabel32.setBounds(130, 30, 110, 0);

        jLabel33.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 204));
        jLabel33.setText("WELCOME");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(140, 30, 400, 21);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("PAYMENT METHODS");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(10, 117, 220, 20);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(0, 255, 51));
        jRadioButton5.setText("CHEQUE");
        jRadioButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton5);
        jRadioButton5.setBounds(220, 110, 110, 31);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(0, 255, 51));
        jRadioButton6.setText("DEBIT CARD");
        jRadioButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton6);
        jRadioButton6.setBounds(610, 110, 160, 31);

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(0, 255, 51));
        jRadioButton7.setText("CREDIT CARD");
        jRadioButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton7);
        jRadioButton7.setBounds(400, 110, 170, 31);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/credit-card.png"))); // NOI18N
        jPanel5.add(jLabel35);
        jLabel35.setBounds(630, 140, 140, 120);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cheque.png"))); // NOI18N
        jPanel5.add(jLabel36);
        jLabel36.setBounds(220, 140, 140, 120);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/credit-card2.png"))); // NOI18N
        jPanel5.add(jLabel37);
        jLabel37.setBounds(410, 140, 140, 120);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 255, 0));
        jButton10.setText("Confirm And Book Ticket");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10);
        jButton10.setBounds(840, 360, 200, 30);

        jLabel38.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 204));
        jLabel38.setText("WELCOME");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(20, 30, 110, 21);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2.jpg"))); // NOI18N
        jPanel5.add(jLabel39);
        jLabel39.setBounds(0, -10, 1080, 410);

        jTabbedPane1.addTab("Payment Details", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 180, 1080, 460);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Tab 1");

        jLabel12.setBackground(new java.awt.Color(0, 0, 204));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(880, 100, 0, 0);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("TICKET ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(480, 20, 270, 100);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);
        jButton11.setBounds(1020, 10, 60, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1100, 630);

        setSize(new java.awt.Dimension(1086, 643));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Connection myconnection;

        try
        {

            myconnection=DriverManager.getConnection(url, username,password);
            
            
            int a,b;
            
            try
            {
                String query="select Flight_ID,Flightname,FlightchargesB,FlightchargesE,Flightclass,Arrivaltime,Departuretime,Bseats,Eseats from flighttable where Source=? and Destination=? and Flightdate=? ";

                PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);

                SimpleDateFormat format2=new SimpleDateFormat("yyyy-MM-dd");

                statement.setString(1, jComboBox2.getSelectedItem().toString());
                statement.setString(2, jComboBox1.getSelectedItem().toString());
                statement.setString(3, format2.format(jDateChooser1.getDate()));
                
                a=1;
                
                ResultSet set=statement.executeQuery();
                
                DefaultTableModel m1=(DefaultTableModel) jTable2.getModel();
                TableColumnModel m2=jTable2.getColumnModel();
                m2.getColumn(2).setPreferredWidth(80);
                m2.getColumn(3).setPreferredWidth(80);
                m2.getColumn(1).setPreferredWidth(100);
                m2.getColumn(0).setPreferredWidth(60);
                jTable2.setRowHeight(40);

                if(set.next())
                {

                    m1.setRowCount(0);
                    do
                    {
                        String name,phone,address,gender,course,sbcourse;
                        name=set.getString("Flight_ID");
                        phone=set.getString("Flightname");
                        course=set.getString("Arrivaltime");
                        sbcourse=set.getString("Departuretime");
                        address=set.getString("FlightchargesE");
                        gender=set.getString("FlightchargesB");
                        int sbcourse2=set.getInt("Eseats");
                        int dob=set.getInt("Bseats");

                        m1.addRow(new Object[]{name,phone,sbcourse,course,address,gender,sbcourse2,dob});
                    }while(set.next());
                }
                    else{
                    m1.setRowCount(0);
                    JOptionPane.showMessageDialog(rootPane,"No Flights Avaliable");
                            }
                
                


                statement.close();
            }
                
            
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
                e.printStackTrace();

            }
            finally
            {
                myconnection.close();
            }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int col=0;
                  int col2=1;int col3=2;int col4=3;
                  int row=jTable2.getSelectedRow();
                  String sno=(String)jTable2.getValueAt(row,col);
                  
            if(jRadioButton1.isSelected() || jRadioButton2.isSelected())
            {
                if(!(jComboBox1.getSelectedItem().equals("") || jComboBox5.getSelectedItem().equals("") || jComboBox2.getSelectedItem().equals("")))
                {
                   if(!jDateChooser1.getDate().toString().equals(""))   
                       try{
                           a=jComboBox2.getSelectedItem().toString();
                b=jComboBox1.getSelectedItem().toString();
                c=sno;
                 jTabbedPane1.setSelectedIndex(1);
                       }
                   catch(Exception e)
                   {
                       JOptionPane.showMessageDialog(rootPane,"Error due to "+e.getMessage());
                   }
                   else
                JOptionPane.showMessageDialog(rootPane,"Fill All Details");
        
                }
                else
                JOptionPane.showMessageDialog(rootPane,"Fill All Details");
        
            }
            else
                JOptionPane.showMessageDialog(rootPane,"Fill All Details");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
if(jComboBox2.getSelectedIndex()>0)
{
                Connection myconnection;
      
        
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="select Destination from flighttable where Source=? and Flighttype=?";
             
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
             statement.setString(1,jComboBox2.getSelectedItem().toString());
             statement.setString(2,jRadioButton1.isSelected()?"Domestic":"International");
             ResultSet set=statement.executeQuery();
             
             if(set.next())
             {
               jComboBox1.removeAllItems();                 
              
               jComboBox1.addItem("Choose Now");
               
                 do
                 {
                     
                            
                            jComboBox1.addItem(set.getString("Destination"));
                         
                 } while(set.next());
                         
            }
            
           
                 
             
             statement.close();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             e.printStackTrace();
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 e.printStackTrace();
                 }
}
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        Connection myconnection;
      
        
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="select Source from flighttable where Flighttype=?";
             
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
             statement.setString(1,"International");
             ResultSet set=statement.executeQuery();
             
             if(set.next())
             {
                                
               jComboBox2.removeAllItems();
                              
               jComboBox2.addItem("Choose Now");
                 
                 do
                 {
                           jComboBox2.addItem(set.getString("Source"));
                           
                         
                 } while(set.next());
                         
            }
                 
             
             statement.close();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             e.printStackTrace();
         }
         finally
         {
             myconnection.close();
         }
}
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 e.printStackTrace();
                 }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        Connection myconnection;
      
        
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="select Source from flighttable where Flighttype=?";
             
             PreparedStatement statement=(PreparedStatement) myconnection.prepareStatement(query);
             statement.setString(1,"Domestic");
             ResultSet set=statement.executeQuery();
             
             if(set.next())
             {
                              
               jComboBox2.removeAllItems();
               
               jComboBox2.addItem("Choose Now");
                 do
                 {
                     
                            jComboBox2.addItem(set.getString("Source"));
                            
                         
                 } while(set.next());
                         
            }
            
             else
                 JOptionPane.showMessageDialog(rootPane,"No Available Flights");
                 
             
             statement.close();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             e.printStackTrace();
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 e.printStackTrace();
                 }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        Creditcard ojb=new Creditcard();
        ojb.setVisible(true);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        Creditcard ojb=new Creditcard();
        ojb.setVisible(true);
                
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed

        Cheque obj=new Cheque();
       obj.setVisible(true);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

                   Connection myconnection;
                
                  int col=0;
                  int col2=1;int col3=2;int col4=3;
                  int row=jTable2.getSelectedRow();
                  String sno=(String)jTable2.getValueAt(row,col);
                
                
                
                d=(String)jTable2.getValueAt(row, col2);
                e=(String)jTable2.getValueAt(row, col3);
                f=(String)jTable2.getValueAt(row, col4);
                g=jDateChooser1.getDate().toString();
                h=jLabel8.getText();
                i=jLabel16.getText();
       
        if(jRadioButton5.isSelected() || jRadioButton6.isSelected() || jRadioButton7.isSelected())
        {
          
        try
        {
            
        myconnection=DriverManager.getConnection(url, username,password);
         try
         {
             String query="insert into ticket2(f_ID,Paymentmode,c_ID,flightclass,datetime) values(?,?,?,?,?)";
             java.sql.PreparedStatement statement=(java.sql.PreparedStatement) myconnection.prepareStatement(query);
             java.util.Date date=new java.util.Date();
             SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
             
             
             statement.setString(1,sno);
             statement.setString(2,jRadioButton5.isSelected()?"Cheque":(jRadioButton7.isSelected()?"Credit Card":"Debit Card"));
              statement.setString(3,jLabel30.getText());
              statement.setString(4,jComboBox5.getSelectedItem().toString());
              statement.setString(5,format.format(date));
              
              int l=1;
              java.sql.PreparedStatement statement2;
              
              
              if(jComboBox5.getSelectedItem().toString().equalsIgnoreCase("Economy"))
              {
                String query2="update flighttable set Eseats=Eseats-? where Flight_ID=?";
                statement2=(java.sql.PreparedStatement) myconnection.prepareStatement(query2);
                statement2.setString(2,c);
                statement2.setInt(1,l);
                statement2.executeUpdate();
               
              }
              else
              {
                  String query2="update flighttable set Bseats=Bseats-? where Flight_ID=?";
                  statement2=(java.sql.PreparedStatement) myconnection.prepareStatement(query2);
                statement2.setInt(1,l);
                statement2.setString(2,c);
                statement2.executeUpdate();
                  
              }
              
                  
              
             if(statement.executeUpdate()>0 && statement2.executeUpdate()>0)
             {
                  
                   
                 PrintTicket obj=new PrintTicket();
                 obj.setVisible(true);
                 this.dispose();
                     
             }
             
             statement.close();
             
             
         
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(rootPane, e.getMessage());
             
         }
         finally
         {
             myconnection.close();
         }
        }
         catch(Exception e)    
                 {
                 JOptionPane.showMessageDialog(rootPane, e.getMessage());
                 }
        }
       
        
        else
            JOptionPane.showMessageDialog(rootPane,"Please Complete Payment Process");

        

        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.dispose();
      
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Connection myconnection;

        try
        {

            myconnection=DriverManager.getConnection(url, username,password);
            try
            {
                String query="select Customer_ID from customertable where Passport=?";
                com.mysql.jdbc.PreparedStatement statement=(com.mysql.jdbc.PreparedStatement) myconnection.prepareStatement(query);
                statement.setString(1,jFormattedTextField3.getText());

                ResultSet set=statement.executeQuery();

                if(set.next())
                {
                    jLabel30.setText(set.getString("Customer_ID"));
                    try
                    {

                        String query1="select * from customertable where Customer_ID=?";
                        com.mysql.jdbc.PreparedStatement statement1=(com.mysql.jdbc.PreparedStatement) myconnection.prepareStatement(query1);
                        statement1.setString(1,jLabel30.getText());

                        j=jLabel30.getText();

                        ResultSet set2=statement1.executeQuery();

                        if(set2.next())
                        {
                            jLabel8.setText(set2.getString("Firstname"));
                            jLabel16.setText(set2.getString("Lastname"));
                            jLabel18.setText(set2.getString("State"));

                            jLabel19.setText(set2.getString("Address"));
                            jLabel20.setText(set2.getString("Phone"));
                            jFormattedTextField3.setText(set2.getString("Passport"));
                            if(set2.getString("Gender").equalsIgnoreCase("Male"))
                            {
                                jRadioButton4.setSelected(true);
                            }
                            else
                            {
                                jRadioButton3.setSelected(true);
                            }

                            jComboBox3.setSelectedItem(set2.getString("Country"));
                            jLabel22.setText(set2.getString("Email"));
                            

                            }

                        }
                        catch(Exception e)
                        {
                            JOptionPane.showMessageDialog(rootPane,e.getMessage());
                        }

                    }
                    else
                    JOptionPane.showMessageDialog(rootPane,"Passport Number Not Found");
                    statement.close();
                }

                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());

                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

       if(jFormattedTextField3.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane,"Fill all details");
        }
        else if(jComboBox1.getSelectedItem().toString().equals(""))

        {
            JOptionPane.showMessageDialog(rootPane,"Fill all details");
        }
        else if(jDateChooser1.getDate().toString().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane,"Fill all details");
        }
        else if(!(jRadioButton1.isSelected() || jRadioButton2.isSelected()))
        {
            JOptionPane.showMessageDialog(rootPane,"Fill all details");
        }

        else
        {

            if(!jLabel30.getText().equals(""))
            {
                jTabbedPane1.setSelectedIndex(2);
                jLabel33.setText(jLabel8.getText()+" "+jLabel16.getText());

            }
            else
            JOptionPane.showMessageDialog(rootPane,"Please fill your details in Add Customer on Home Page");

        }

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
